name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: arumadzu/my-api:latest

    - name: Deploy Docker container
      run: |
        docker pull arumadzu/my-api:latest
        docker stop api_container || true
        docker rm api_container || true
        docker run -d --name api_container -p 80:80 arumadzu/my-api:latest
