name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, sync-agent]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run deploy script
        run: |
          ./deploy.sh

